name: 'Greetings'

on:
  fork:
  push:
    branches: [main]
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Welcome, @${{ github.actor }}! Thanks for raising the issue! We'll look into it right away. 🛠️"
          pr-message: 'Great job, @${{ github.actor }}! Thanks for creating the pull request! We'll review it shortly. 🙌'